import json
import os
from typing import Optional

import typer
from rich.console import Console

from .scanner import scan_directory
from .profiler import generate_profile
from .searcher import search_repositories
from .reporter import generate_report

app = typer.Typer(
    help='ADS CodeDetective — Software Supply Chain Monitoring',
    add_completion=False,
)
console = Console()


@app.command()
def scan(
    directory: str = typer.Argument(..., help='Directory to scan'),
    output: str = typer.Option(
        'detectables.cd', '--output', '-o',
        help='Output path for the .cd profile (JSON)',
    ),
):
    """
    Scan a directory and generate a fingerprint profile (.cd file).

    The profile captures:
      - SHA-256 / MD5 / SHA-1 / SHA-512 hashes per file
      - Winnowing structural fingerprints (MOSS-style)
      - Function/class/import identifiers (multi-language)
      - TF-IDF ML feature vector
      - Neural autoencoder embedding (if torch is installed)
    """
    console.print(f'[bold green]Scanning:[/bold green] {directory}')

    with console.status('Scanning files and computing fingerprints …'):
        fingerprints = scan_directory(directory)

    console.print(f'  Found [bold]{len(fingerprints)}[/bold] processable files.')

    with console.status('Building profile (TF-IDF + neural embedding) …'):
        profile = generate_profile(fingerprints, directory)

    with open(output, 'w') as fh:
        json.dump(profile, fh, indent=2)

    langs     = profile.get('languages', {})
    top_langs = sorted(langs.items(), key=lambda x: -x[1])[:5]
    lang_str  = ', '.join(f'{k}({v})' for k, v in top_langs)

    console.print(f'  Languages:                {lang_str}')
    console.print(f'  Identifiers extracted:    [bold]{len(profile.get("identifiers", []))}[/bold]')
    console.print(f'  Winnowing fingerprints:   [bold]{len(profile.get("winnow_fingerprint", []))}[/bold]')
    console.print(f'  Total size:               {profile.get("total_size_bytes", 0) // 1024} KB')
    console.print(f'[bold green]Profile saved to:[/bold green] {output}')


@app.command()
def investigate(
    profile_path: str = typer.Argument(
        'detectables.cd',
        help='Path to a .cd profile file produced by the scan command',
    ),
    threshold: float = typer.Option(
        0.15, '--threshold', '-t',
        help='Minimum composite similarity score to include in results (0–1)',
    ),
    json_out: Optional[str] = typer.Option(
        None, '--json',
        help='Save a machine-readable JSON report to this path',
    ),
):
    """
    Search GitHub for repositories that may be copies of a scanned codebase.

    Requires the GITHUB_TOKEN environment variable to be set for real search.
    Without it, a demo result is returned.

    Similarity is scored across three signals:
      hash_overlap (40%)     — exact byte-for-byte file matches
      winnow_jaccard (35%)   — structural similarity after normalization
      identifier_overlap (25%) — shared function/class/import names
    """
    if not os.path.exists(profile_path):
        console.print(f'[bold red]Error:[/bold red] Profile not found: {profile_path}')
        raise typer.Exit(1)

    with open(profile_path) as fh:
        profile = json.load(fh)

    schema_ver = profile.get('version', '1.0')
    if schema_ver < '2.0':
        console.print(
            '[yellow]Warning:[/yellow] This profile was generated by an older version of '
            'CodeDetective.  Re-run [bold]codedetective scan[/bold] for best results.'
        )

    console.print(f'[bold green]Investigating:[/bold green] {profile_path}')
    console.print(
        f'  {profile.get("total_files", "?")} files · '
        f'{len(profile.get("identifiers", []))} identifiers · '
        f'{len(profile.get("winnow_fingerprint", []))} fingerprint hashes · '
        f'threshold={threshold}'
    )

    if not os.environ.get('GITHUB_TOKEN'):
        console.print(
            '[yellow]Note:[/yellow] GITHUB_TOKEN not set — running in demo mode.'
        )

    with console.status('Searching GitHub …'):
        matches = search_repositories(profile, threshold=threshold)

    generate_report(matches, profile=profile, json_output=json_out)


if __name__ == '__main__':
    app()
